#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     angle,          sensorI2CCustomFastSkipStates)
#pragma config(Sensor, S4,     irsensor,       sensorI2CCustomFastSkipStates)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    rampGate,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    gripper,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    rampLaunchL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    rampLaunchR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Copyright (c) 2013 Pope John XXIII High School Robotics Team

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in the
Software without restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#include "248header.h"

task main() {
	int batDelta = externalBatteryAvg-13700;
	writeDebugStreamLine("BAT: %d",batDelta);
	HTIRS2setDSPMode(irsensor, DSP_1200);
	int p_start = -254;
	waitForStart();
  forwardForTimeAndStop(100,1200+-batDelta/27);
  wait1Msec(100);
  turnLeftForGyroAndStop(100,47);

  int irArray[5];
  HTIRS2readAllACStrength(irsensor, irArray[0], irArray[1], irArray[2], irArray[3], irArray[4]);
  int guess = 1337;
  if (irArray[3] > 0) guess = 1;
  else if (irArray[1] > 0 || irArray[2] < 90) guess = -1;
  else guess = 0;

  writeDebugStreamLine("%d, %d, %d, %s",irArray[1],irArray[2],irArray[3],guess==1?"RIGHT":(guess==-1?"LEFT":"CENTER OR FAILURE"));
  PlayImmediateTone(guess?(guess==1?2000:500):1000,10);
  wait1Msec(400);
  switch (guess){
  	case -1:// LEFT
  		turnLeftForGyroAndStop(100,45);
  		motor[lift] = 100;
  		wait1Msec(2700+-batDelta/26);
  		motor[lift] = 20;
  		forwardForTimeAndStop(100,1000+-batDelta/27);
  		turnLeftForGyroAndStop(-100,43);
  		HTIRS2readAllACStrength(irsensor, irArray[0], irArray[1], irArray[2], irArray[3], irArray[4]);
  		writeDebugStreamLine("BEFORE RE-ALIGN: %d, %d, %d",irArray[1],irArray[2],irArray[3]);
  		while (irArray[1] > 60 || irArray[2] > 162){
  			rightSide(40);
  			 leftSide(-40);
  			HTIRS2readAllACStrength(irsensor, irArray[0], irArray[1], irArray[2], irArray[3], irArray[4]);
  		}
  		writeDebugStreamLine("AFTER RE-ALIGN: %d, %d, %d",irArray[1],irArray[2],irArray[3]);
  		forwardForTimeAndStop(75,1320+-batDelta/27);
  		PlayTone(1000,1000);
  		PlayTone(200 ,1000);
  		motor[lift] = -30;
  		ClearTimer(T2);
  		while (time1[T2] < 10000){
  			rightSide( 31);
  			 leftSide(-30);
  			wait1Msec(300);
  			rightSide(-30);
  			 leftSide( 31);
  			wait1Msec(300);
  			 if (time1[T2]>500) motor[lift] = -8;
  		}
  		motor[lift] = 10;
  		break;
  	case 0://  CENTER
  		turnLeftForGyroAndStop(100,45);
  		motor[lift] = 100;
  		wait1Msec(2700+-batDelta/26);
  		motor[lift] = 20;
  		forwardForTimeAndStop(100,1100+-batDelta/26);
  		turnLeftForGyroAndStop(-100,86);
  		forwardForTimeAndStop(100,1240+-batDelta/26);
  		/*turnLeftForGyroAndStop(-100,45);
  		forwardForTimeAndStop(100,800+-batDelta/27);
  		turnLeftForGyroAndStop(100,110);
  		forwardForTimeAndStop(75,540+-batDelta/26);
  		PlayTone(1000,1000);
  		PlayTone(200 ,1000);
  		*/
  		motor[lift] = -30;
  		ClearTimer(T2);
  		while (time1[T2] < 12000){
  			rightSide( 30);
  			 leftSide(-30);
  			wait1Msec(300);
  			rightSide(-30);
  			 leftSide( 30);
  			wait1Msec(300);
  			 if (time1[T2]>500) motor[lift] = -4;
  		}
  		motor[lift] = 10;
  		break;
  	case 1://  RIGHT
  		turnLeftForGyroAndStop(-100,45);
  		motor[lift] = 100;
  		wait1Msec(2700+-batDelta/26);
  		motor[lift] = 20;
  		forwardForTimeAndStop(100,1720+-batDelta/26);
  		turnLeftForGyroAndStop(100,51);
  		HTIRS2readAllACStrength(irsensor, irArray[0], irArray[1], irArray[2], irArray[3], irArray[4]);
  		writeDebugStreamLine("BEFORE RE-ALIGN: %d, %d, %d",irArray[1],irArray[2],irArray[3]);
  		while (irArray[1] > 60 || irArray[2] > 162){
  			rightSide(40);
  			 leftSide(-40);
  			HTIRS2readAllACStrength(irsensor, irArray[0], irArray[1], irArray[2], irArray[3], irArray[4]);
  		}
  		writeDebugStreamLine("AFTER RE-ALIGN: %d, %d, %d",irArray[1],irArray[2],irArray[3]);
  		turnLeftForGyroAndStop(-100,3);
  		forwardForTimeAndStop(75,650+-batDelta/26);
  		PlayTone(1000,1000);
  		PlayTone(200 ,1000);
  		motor[lift] = -30;
  		ClearTimer(T2);
  		while (time1[T2] < 10000){
  			rightSide( 31);
  			 leftSide(-30);
  			wait1Msec(300);
  			rightSide(-30);
  			 leftSide( 31);
  			wait1Msec(300);
  			 if (time1[T2]>500) motor[lift] = -8;
  		}
  		motor[lift] = 10;
  		break;
  }
}
